baseURL = "https://hludovic.github.io/Portfolio/"
languageCode = "en-us"
title = "Ludovic Henry"
theme = "alexa-portfolio"
googleAnalytics = "UA-167869327-1"
enableRobotsTXT = true
canonifyURLs = true

[params]
	favicon = "favicon-32x32.png"
	home_title = "Bonjour, Je suis Ludovic"
	home_subtitle = "Développeur iOS"
	home_description = "and also has little experience in Mobile development and Design."
	github = "https://github.com/hludovic"
	linkedin = "https://www.linkedin.com/in/hludovic/"
	dribbble = ""
	phone = "0011223344"
	email = "temp@gmail.com"
	location = "Guadeloupe, France"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true