baseURL = "https://www.hludovic.fr/"
languageCode = "fr-FR"
title = "Ludovic Henry"

[params]
	favicon = "/images/favicon-32x32.png"
	home_title = "Bonjour, Je suis Ludovic."
	home_subtitle = "Freelance - Développeur Mobile - iOS Natif"
	home_description = "J'utilise mes superpouvoirs pour construire des produits délicieux."
	github = "https://github.com/hludovic"
	linkedin = "https://www.linkedin.com/in/hludovic/"
	email = "temp@gmail.com"
	location = "Guadeloupe, France"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true